site_name: AdminTools
theme:
    name: slate
    nav_style: dark
markdown_extensions:
    - toc:
        permalink: #
    - tables
    - admonition
    - def_list
    - footnotes
    - mdx_gh_links:
        user: LukeOnuke
        repo: AdminTools