site_name: AdminTools
theme_dir: material/
theme:
    name: null
    custom_dir: 'material'
    highlightjs: true
    hljs_languages:
        - java
        - css
        - xml
        - json
markdown_extensions:
    - toc:
        permalink: #
    - tables
    - admonition
    - def_list
    - mdx_gh_links:
        user: LukeOnuke
        repo: AdminTools