site_name: AdminTools
theme:
    name: cerulean
    nav_style: dark
    highlightjs: true
    hljs_languages:
        - java
        - css
        - xml
        - json
markdown_extensions:
    - toc:
        permalink: #
    - tables
    - admonition
    - def_list
    - mdx_gh_links:
        user: LukeOnuke
        repo: AdminTools