# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Set up dependencies | rkon-core
      run: mvn install:install-file -Dfile=https://github.com/Pequla/RconCore/releases/download/v1.2/rkon-core-1.2.jar -DgroupId=net.kronos -DartifactId=rkon-core -Dversion=1.1.2 -Dpackaging=jar -DgeneratePom=true
    - name: Set up dependencies | simplefxdialog
      run: mvn install:install-file -Dfile=https://github.com/LukeOnuke/SimpleFxDialog/releases/download/v2.0.0/SimpleFxDialog.jar -DgroupId=com.lukeonuke -DartifactId=simplefxdialog -Dversion=2.0.0 -Dpackaging=jar -DgeneratePom=true
    - name: Build with Maven
      run: mvn -B package --file pom.xml
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Set up dependencies | rkon-core
      run: mvn install:install-file -Dfile=https://github.com/Pequla/RconCore/releases/download/v1.2/rkon-core-1.2.jar -DgroupId=net.kronos -DartifactId=rkon-core -Dversion=1.1.2 -Dpackaging=jar -DgeneratePom=true
    - name: Set up dependencies | simplefxdialog
      run: mvn install:install-file -Dfile=https://github.com/LukeOnuke/SimpleFxDialog/releases/download/v2.0.0/SimpleFxDialog.jar -DgroupId=com.lukeonuke -DartifactId=simplefxdialog -Dversion=2.0.0 -Dpackaging=jar -DgeneratePom=true
    - name: Build with Maven
      run: mvn -B package --file pom.xml
  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Set up dependencies | rkon-core
      run: mvn install:install-file -Dfile=https://github.com/Pequla/RconCore/releases/download/v1.2/rkon-core-1.2.jar -DgroupId=net.kronos -DartifactId=rkon-core -Dversion=1.1.2 -Dpackaging=jar -DgeneratePom=true
    - name: Set up dependencies | simplefxdialog
      run: mvn install:install-file -Dfile=https://github.com/LukeOnuke/SimpleFxDialog/releases/download/v2.0.0/SimpleFxDialog.jar -DgroupId=com.lukeonuke -DartifactId=simplefxdialog -Dversion=2.0.0 -Dpackaging=jar -DgeneratePom=true
    - name: Build with Maven
      run: mvn -B package --file pom.xml
